have_fun: false
code_review_config:
  enabled: true
  default_severity: MEDIUM
  max_comments_per_file: 50
  max_comments_per_pull_request: 100
  comment_severity_threshold: MEDIUM
  pull_request_opened:
    help: true
    summary: true
    code_review: true
  ignore_patterns: [.lock, .DS_Store, .git, .github, .idea, .vscode, .settings, .project, .classpath, .rs.bk, target, .exercism]